export const en = {
  nav: {
    home: "Home",
    account: "Account",
    settings: "Settings",
    openAccount: "Open account",
  },
  common: {
    partners: "Partners",
    sarawakOnly: "Sarawak only",
    back: "Back",
    loading: "Loading...",
    openArrow: "Open →",
    required: "Required",
    optional: "Optional",
    done: "Done",
    incomplete: "Incomplete",
    save: "Save",
    saving: "Saving...",
    continue: "Continue",
    saveAndContinue: "Save and continue",
    saveProfile: "Save Profile",
    continueArrow: "Continue →",
    completeRequiredFields: "Complete required fields to continue.",
    yes: "Yes",
    no: "No",
    notSure: "Not sure",
    email: "Email",
    password: "Password",
    name: "Name",
  },
  theme: {
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  fontSize: {
    small: "Small",
    medium: "Medium",
    large: "Large",
    largePlus: "Large+",
  },
  msicPicker: {
    title: "Select Industry (MSIC)",
    subtitle: "Search by code or name",
    searchPlaceholder: "Search MSIC code (e.g. 47110) or name (e.g. retail)",
    recent: "Recent:",
    examples: "Examples:",
    startTyping: "Start typing to search for MSIC codes or industry names.",
    browseBySection: "Browse by Section (A–U)",
    selectMsicCode: "Select MSIC code",
    searching: "Searching...",
    noResults: "No results. Try a different keyword.",
    noResultsLong: "No results. Type more characters or try a different keyword.",
  },
  toast: {
    saved: "Saved",
    updated: "Updated",
    industrySet: "Industry set",
    failedToLoadProfile: "Failed to load profile",
    failedToSaveTryAgain: "Failed to save. Please try again.",
    couldNotSaveTryAgain: "Couldn't save right now. Please try again.",
  },
  settings: {
    title: "Settings",
    subtitle: "Extra configuration for later releases.",
    prototypeOnlyTitle: "Prototype only",
    prototypeOnlyBody:
      "In a later version this screen can hold advanced preferences. For now, use the Account tab to access profile, language and theme.",
  },
  dashboard: {
    title: "Profile",
    subtitle: "Quick view of your setup and next step.",
    requiredMessage: "Required: Company size and MSIC to use Invoice Check.",
    completeMessage: "Profile complete. You can use Invoice Check.",
    allStepsCompleted: "All steps completed",
    finishToContinue: "Finish business details and industry to continue.",
  },
  setup: {
    title: "Business profile",
    progressOf: "of",
    progressCompleted: "completed",
    completeToUnlock: "Complete these to unlock Tax Check.",
    step: {
      business: { title: "Business details", subtitle: "Name, company, size" },
      industry: { title: "Industry (MSIC)", subtitle: "Your main economic activity" },
      optional: { title: "SST status", subtitle: "SST registration details" },
    },
    optionalCard: {
      title: "SST status",
    },
  },
  setupBusiness: {
    title: "Profile",
    subtitle: "Enter your business information.",
    namePlaceholder: "Your name",
    companyNameLabel: "Company name",
    companyNamePlaceholder: "e.g. Acme Sdn Bhd",
    companySizeLabel: "Company Size last year",
    companySizePlaceholder: "Select company size",
    companySize: {
      micro: "Micro",
      small: "Small",
      medium: "Medium",
    },
  },
  setupOptional: {
    title: "SST Registration (Optional)",
    subtitle: "Helps us give more accurate results. You can skip this and still use Tax Check.",
    info: {
      whyWeAsk: {
        title: "Why we ask",
        body: "If you're SST-registered, we can show results with clearer compliance notes (e.g., input tax credit eligibility / registration context).",
      },
      ifYouSkip: {
        title: "If you skip",
        body: "We'll still run Tax Check, but results may be less specific.",
      },
      whereToFind: {
        title: "Where to find this",
        body: "Check your SST registration certificate / portal / accountant. SST number usually starts with 'SST'.",
      },
    },
    question: "Are you SST-registered?",
    notSureHint: "Choose 'Not sure' if you don't know yet.",
    sstNumberLabel: "SST registration number",
    sstNumberPlaceholder: "e.g., SST-XXXXXXX",
    effectiveDateLabel: "Effective date",
    effectiveDateHint: "Effective date = date your registration becomes active.",
    errors: {
      sstNumberRequired: "SST number is required",
      effectiveDateRequired: "Effective date is required",
    },
    noMessage: "You can still use Tax Check. We'll treat you as not registered.",
    notSureMessage: "No problem — you can update this later in Settings.",
  },
  setupIndustry: {
    title: "Industry (MSIC)",
    subtitle: "Search by MSIC code or name.",
    sectionTitle: "Industry (MSIC)",
    errors: { msicRequired: "MSIC selection is required." },
    loadingIndustryDetails: "Loading industry details...",
    selectedIndustry: "Selected Industry",
    industryCodeNotFoundPrefix: "Industry code",
    industryCodeNotFoundSuffix: "not found",
    viewScope: "View scope",
    scopeTitle: "Scope of Economic Activities",
    scope: {
      section: "Section",
      division: "Division",
      group: "Group",
      class: "Class",
    },
    itemSearch: {
      title: "Item (optional)",
      hint: "Type an item name (e.g. 'keyboard') to find its MSIC automatically.",
      placeholder: "e.g. keyboard, printer, etc.",
      noMsic: "This item has no MSIC yet. Please select an industry manually or go one level up.",
      notFound: "No match for this item. Please try a broader keyword or go one level up.",
      msicNotFound: "MSIC code not found for this item.",
      msicAlreadySelected: "MSIC already selected — clear it to use item's MSIC.",
      unclassifiedBadge: "Unclassified",
      addUnclassifiedLink: "Add this as a new unclassified item",
    },
    invoice: {
      type: "Type",
      sales: "Sales",
      cost: "Cost",
      item: "Item",
      itemsHint: "Items are based on your selected MSIC scope.",
      noItemsAvailable: "No items available",
      itemPlaceholder: "Search or select item...",
      checking: "Checking...",
      checkInvoice: "Check invoice",
      checkTaxPercent: "Check tax % for invoice",
    },
    result: {
      sstRateNotAvailable: "SST rate not available yet.",
      noResultTitle: "No result for this item right now",
      tryMsicLevel: "Please try at MSIC level",
    },
  },
  auth: {
    emailPlaceholder: "you@example.com",
    login: {
      title: "Welcome back",
      subtitle: "Sign in to your SmartTaxApp account",
      signingIn: "Signing in...",
      signIn: "Sign in",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
      forgotPassword: "Forgot password?",
      unexpectedError: "An unexpected error occurred. Please try again.",
    },
    resetPassword: {
      title: "Forgot password",
      subtitle: "Enter your email to receive a 6-digit code",
      helper: "We'll send a code to the email used during signup.",
      emailHint: "We'll send a code to {email}",
      sending: "Sending...",
      sendCode: "Send code",
      sendResetLink: "Send reset link",
      resendCode: "Resend code",
      resendIn: "Resend in {seconds}",
      backToLogin: "Back to login",
      changeEmail: "Change email",
      codeSentMessage: "We sent a 6-digit code to your email.",
      useLatestCodeHint: "Use the latest code we sent.",
      stepBTitle: "Enter code and set new password",
      codeLabel: "6-digit code",
      codePlaceholder: "000000",
      resetPasswordButton: "Reset password",
      resetting: "Resetting...",
      successTitle: "Password updated",
      successMessage: "Go to login.",
      invalidOrExpiredCode: "Invalid or expired code. Use the latest code we sent and try again.",
      sessionMissingAfterVerify: "Could not verify code. Please request a new code.",
      couldntUpdatePassword: "Couldn't update password. Try again.",
      success: {
        title: "Check your email",
        message: "We sent a 6-digit code to your email.",
        didntReceiveSendAgain: "Didn't receive the email? Resend code.",
      },
      errors: {
        emailRequired: "Email is required.",
        codeRequired: "Enter the 6-digit code.",
        codeMustBe6Digits: "Code must be 6 digits.",
        passwordTooShort: "Password must be at least 6 characters.",
        passwordsDoNotMatch: "Passwords do not match.",
        unexpectedError: "Network or auth error. Check connection and try again.",
        networkError: "Network error. Check your connection and try again.",
      },
    },
    resetPasswordConfirm: {
      title: "Set new password",
      subtitle: "Enter your new password below.",
      newPasswordLabel: "New password",
      confirmPasswordLabel: "Confirm password",
      submit: "Update password",
      updating: "Updating...",
      loading: "Verifying reset link...",
      successTitle: "Password updated",
      successMessage: "Redirecting you to sign in...",
      backToLogin: "Back to login",
      didntReceiveSendAgain: "Didn't receive the email? Send again.",
      requestNewLink: "Request new link",
      goToForgotPassword: "Forgot password",
      errorNoLink: "No reset link detected. Use the link from your email.",
      errorInvalidExpired: "This link is invalid or has expired. Request a new one.",
      errorExpiredTitle: "Reset link invalid or expired",
      errorExpiredExplanation: "This link is single-use and may have been opened by your email client's security scanner before you clicked it.",
      errorExpiredTip1: "Request a new link and open it immediately",
      errorExpiredTip2: "Open the email on your phone, a different client, or in an incognito/private window",
      errorExpiredTip3: "Copy the reset URL from the email and paste it into your browser address bar (avoid in-app email preview)",
      openLinkManuallyTitle: "Open link manually",
      openLinkManuallyInstructions: "Copy the reset URL from your email and paste it into your browser address bar. Avoid opening links inside email preview webviews.",
      errors: {
        passwordTooShort: "Password must be at least 6 characters.",
        passwordsDoNotMatch: "Passwords do not match.",
        unexpectedError: "Network or auth error. Please try again.",
      },
    },
    signup: {
      title: "Create account",
      subtitle: "Sign up to get started with SmartTaxApp",
      passwordHint: "Must be at least 6 characters",
      confirmPasswordLabel: "Confirm Password",
      creatingAccount: "Creating account...",
      signUp: "Sign up",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
      success: {
        checkEmailToConfirm: "Account created. Check your email to confirm.",
      },
      errors: {
        invalidEmail: "Please enter a valid email.",
        passwordTooShort: "Password must be at least 6 characters.",
        passwordsDoNotMatch: "Passwords do not match.",
        passwordsDoNotMatchInline: "Passwords do not match",
        networkError:
          "Network error: unable to reach authentication service. Check connection and Supabase env variables.",
        signUpFailed: "Sign up failed. Please try again.",
      },
    },
  },
  admin: {
    addUnclassifiedTitle: "Add Item (Unclassified)",
    addUnclassifiedSubtitle: "Add the new item with no MSIC for our team to update for future update.",
    itemNameLabel: "Item name",
    itemNamePlaceholder: "e.g. Glue stick",
    tagsLabel: "Tags",
    tagsPlaceholder: "e.g. office, supplies",
    tagsHint: "Comma-separated tags for search",
    submit: "Submit",
    submitting: "Submitting...",
    successTitle: "Submitted",
    successThankYou: "Thanks! Our team will review it.",
    addAnother: "Add another",
    toastItemNameRequired: "Item name is required.",
    backToSettings: "← Back to Settings",
  },
  account: {
    title: "Account",
    subtitle: "Settings for your profile and app experience.",
    backToDashboard: "Back to dashboard",
    profile: {
      title: "Profile",
      description: "Quick links to your core setup.",
      setup: "Profile setup",
    },
    changePassword: {
      title: "Change password",
      description: "Update your password. No email will be sent.",
      currentPasswordLabel: "Current password",
      currentPasswordOptional: "(optional)",
      newPasswordLabel: "New password",
      confirmPasswordLabel: "Confirm password",
      submit: "Update password",
      updating: "Updating...",
      success: "Password updated.",
      changePasswordCta: "Change password",
      passwordHint: "At least 6 characters.",
      errors: {
        newPasswordRequired: "New password is required.",
        passwordTooShort: "Password must be at least 6 characters.",
        passwordsDoNotMatch: "Passwords do not match.",
        currentPasswordIncorrect: "Current password is incorrect.",
        unexpectedError: "Could not update password. Please try again.",
      },
    },
    password: {
      title: "Password",
      description: "Change your password or request a reset link sent to your email.",
      helper: "For security, we don't email your password. You'll set a new one.",
      changePasswordCta: "Change password now",
      sendResetInstead: "Send password reset email",
      cancel: "Cancel",
      sendResetEmail: "Send reset link",
      sending: "Sending...",
      success: "Check your email for a reset link.",
    },
    settings: {
      title: "Settings",
      description: "How SmartTaxApp looks and feels.",
      language: "Language",
      theme: "Theme",
      fontSize: "Font Size",
      languageOptions: {
        en: "English",
        ms: "Bahasa Melayu",
        iban: "Iban (Coming soon)",
        zh: "中文 (Coming soon)",
      },
    },
    support: {
      title: "Support & security",
      description: "Help for you and protection for your data.",
      help: "Help & feedback",
      whatsAppCta: "Chat",
      soon: "Soon",
      security: "Security & privacy",
      placeholder: "Placeholder",
      signOut: "Sign out",
    },
  },
};
