export const en = {
  nav: {
    home: "Home",
    account: "Account",
    settings: "Settings",
    openAccount: "Open account",
  },
  common: {
    partners: "Partners",
    sarawakOnly: "Sarawak only",
    back: "Back",
    loading: "Loading...",
    openArrow: "Open →",
    required: "Required",
    optional: "Optional",
    done: "Done",
    incomplete: "Incomplete",
    save: "Save",
    saving: "Saving...",
    continue: "Continue",
    saveAndContinue: "Save and continue",
    saveProfile: "Save Profile",
    continueArrow: "Continue →",
    completeRequiredFields: "Complete required fields to continue.",
    yes: "Yes",
    no: "No",
    notSure: "Not sure",
    email: "Email",
    password: "Password",
    name: "Name",
  },
  theme: {
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  fontSize: {
    small: "Small",
    medium: "Medium",
    large: "Large",
    largePlus: "Large+",
  },
  msicPicker: {
    title: "Select Industry (MSIC)",
    subtitle: "Search by code or name",
    searchPlaceholder: "Search MSIC code (e.g. 47110) or name (e.g. retail)",
    recent: "Recent:",
    examples: "Examples:",
    startTyping: "Start typing to search for MSIC codes or industry names.",
    browseBySection: "Browse by Section (A–U)",
    selectMsicCode: "Select MSIC code",
    searching: "Searching...",
    noResults: "No results. Try a different keyword.",
    noResultsLong: "No results. Type more characters or try a different keyword.",
  },
  toast: {
    saved: "Saved",
    updated: "Updated",
    industrySet: "Industry set",
    failedToLoadProfile: "Failed to load profile",
    failedToSaveTryAgain: "Failed to save. Please try again.",
    couldNotSaveTryAgain: "Couldn't save right now. Please try again.",
  },
  settings: {
    title: "Settings",
    subtitle: "Extra configuration for later releases.",
    prototypeOnlyTitle: "Prototype only",
    prototypeOnlyBody:
      "In a later version this screen can hold advanced preferences. For now, use the Account tab to access profile, language and theme.",
  },
  dashboard: {
    title: "Profile",
    subtitle: "Quick view of your setup and next step.",
    requiredMessage: "Required: Company size and MSIC to use Invoice Check.",
    completeMessage: "Profile complete. You can use Invoice Check.",
    allStepsCompleted: "All steps completed",
    finishToContinue: "Finish business details and industry to continue.",
  },
  setup: {
    title: "Business profile",
    progressOf: "of",
    progressCompleted: "completed",
    completeToUnlock: "Complete these to unlock Tax Check.",
    step: {
      business: { title: "Business details", subtitle: "Name, company, size" },
      industry: { title: "Industry (MSIC)", subtitle: "Your main economic activity" },
      optional: { title: "SST status", subtitle: "SST registration details" },
    },
    optionalCard: {
      title: "SST status",
    },
  },
  setupBusiness: {
    title: "Profile",
    subtitle: "Enter your business information.",
    namePlaceholder: "Your name",
    companySizeLabel: "Company Size last year",
    companySizePlaceholder: "Select company size",
    companySize: {
      micro: "Micro",
      small: "Small",
      medium: "Medium",
    },
  },
  setupOptional: {
    title: "SST Registration (Optional)",
    subtitle: "Helps us give more accurate results. You can skip this and still use Tax Check.",
    info: {
      whyWeAsk: {
        title: "Why we ask",
        body: "If you're SST-registered, we can show results with clearer compliance notes (e.g., input tax credit eligibility / registration context).",
      },
      ifYouSkip: {
        title: "If you skip",
        body: "We'll still run Tax Check, but results may be less specific.",
      },
      whereToFind: {
        title: "Where to find this",
        body: "Check your SST registration certificate / portal / accountant. SST number usually starts with 'SST'.",
      },
    },
    question: "Are you SST-registered?",
    notSureHint: "Choose 'Not sure' if you don't know yet.",
    sstNumberLabel: "SST registration number",
    sstNumberPlaceholder: "e.g., SST-XXXXXXX",
    effectiveDateLabel: "Effective date",
    effectiveDateHint: "Effective date = date your registration becomes active.",
    errors: {
      sstNumberRequired: "SST number is required",
      effectiveDateRequired: "Effective date is required",
    },
    noMessage: "You can still use Tax Check. We'll treat you as not registered.",
    notSureMessage: "No problem — you can update this later in Settings.",
  },
  setupIndustry: {
    title: "Industry (MSIC)",
    subtitle: "Search by MSIC code or name.",
    sectionTitle: "Industry (MSIC)",
    errors: { msicRequired: "MSIC selection is required." },
    loadingIndustryDetails: "Loading industry details...",
    selectedIndustry: "Selected Industry",
    industryCodeNotFoundPrefix: "Industry code",
    industryCodeNotFoundSuffix: "not found",
    viewScope: "View scope",
    scopeTitle: "Scope of Economic Activities",
    scope: {
      section: "Section",
      division: "Division",
      group: "Group",
      class: "Class",
    },
    invoice: {
      type: "Type",
      sales: "Sales",
      cost: "Cost",
      item: "Item",
      itemsHint: "Items are based on your selected MSIC scope.",
      noItemsAvailable: "No items available",
      itemPlaceholder: "Search or select item...",
      checking: "Checking...",
      checkInvoice: "Check invoice",
    },
    result: {
      sstRateNotAvailable: "SST rate not available yet.",
      noResultTitle: "No result for this item right now",
      tryMsicLevel: "Please try at MSIC level",
    },
  },
  auth: {
    emailPlaceholder: "you@example.com",
    login: {
      title: "Welcome back",
      subtitle: "Sign in to your SmartTaxApp account",
      signingIn: "Signing in...",
      signIn: "Sign in",
      noAccount: "Don't have an account?",
      signUp: "Sign up",
      unexpectedError: "An unexpected error occurred. Please try again.",
    },
    signup: {
      title: "Create account",
      subtitle: "Sign up to get started with SmartTaxApp",
      passwordHint: "Must be at least 6 characters",
      confirmPasswordLabel: "Confirm Password",
      creatingAccount: "Creating account...",
      signUp: "Sign up",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
      success: {
        checkEmailToConfirm: "Account created. Check your email to confirm.",
      },
      errors: {
        invalidEmail: "Please enter a valid email.",
        passwordTooShort: "Password must be at least 6 characters.",
        passwordsDoNotMatch: "Passwords do not match.",
        passwordsDoNotMatchInline: "Passwords do not match",
        networkError:
          "Network error: unable to reach authentication service. Check connection and Supabase env variables.",
        signUpFailed: "Sign up failed. Please try again.",
      },
    },
  },
  admin: {
    addUnclassifiedTitle: "Add Item (Unclassified)",
    addUnclassifiedSubtitle: "Create a new item with no MSIC. It will appear in items_missing_msic export.",
    itemKeyLabel: "Item key",
    itemKeyPlaceholder: "e.g. E2E_TEST_20250212",
    nameEnLabel: "Name (English)",
    nameEnPlaceholder: "e.g. Test Item",
    nameMsLabel: "Name (Malay)",
    nameMsPlaceholder: "Optional",
    tagsLabel: "Tags (comma-separated)",
    tagsPlaceholder: "e.g. test, unclassified",
    submit: "Create Item",
    submitting: "Creating...",
    successTitle: "Item created",
    successMessage: "Run export script or wait for Sunday to generate CSV.",
    backToSettings: "← Back to Settings",
  },
  account: {
    title: "Account",
    subtitle: "Settings for your profile and app experience.",
    backToDashboard: "Back to dashboard",
    profile: {
      title: "Profile",
      description: "Quick links to your core setup.",
      setup: "Profile setup",
    },
    settings: {
      title: "Settings",
      description: "How SmartTaxApp looks and feels.",
      language: "Language",
      theme: "Theme",
      fontSize: "Font Size",
      languageOptions: {
        en: "English",
        ms: "Bahasa Melayu",
        iban: "Iban (Coming soon)",
        zh: "中文 (Coming soon)",
      },
    },
    support: {
      title: "Support & security",
      description: "Help for you and protection for your data.",
      help: "Help & feedback",
      soon: "Soon",
      security: "Security & privacy",
      placeholder: "Placeholder",
      signOut: "Sign out",
    },
  },
};
