export const ms = {
  nav: {
    home: "Utama",
    account: "Akaun",
    settings: "Tetapan",
    openAccount: "Buka akaun",
  },
  common: {
    partners: "Rakan kongsi",
    sarawakOnly: "Sarawak sahaja",
    back: "Kembali",
    loading: "Memuatkan...",
    openArrow: "Buka →",
    required: "Wajib",
    optional: "Pilihan",
    done: "Selesai",
    incomplete: "Belum lengkap",
    save: "Simpan",
    saving: "Menyimpan...",
    continue: "Teruskan",
    saveAndContinue: "Simpan dan teruskan",
    saveProfile: "Simpan profil",
    continueArrow: "Teruskan →",
    completeRequiredFields: "Lengkapkan medan wajib untuk teruskan.",
    yes: "Ya",
    no: "Tidak",
    notSure: "Tidak pasti",
    email: "E-mel",
    password: "Kata laluan",
    name: "Nama",
  },
  theme: {
    light: "Cerah",
    dark: "Gelap",
    system: "Sistem",
  },
  fontSize: {
    small: "Kecil",
    medium: "Sederhana",
    large: "Besar",
    largePlus: "Besar+",
  },
  msicPicker: {
    title: "Pilih Industri (MSIC)",
    subtitle: "Cari menggunakan kod atau nama",
    searchPlaceholder: "Cari kod MSIC (cth. 47110) atau nama (cth. runcit)",
    recent: "Terkini:",
    examples: "Contoh:",
    startTyping: "Mula menaip untuk mencari kod MSIC atau nama industri.",
    browseBySection: "Lihat mengikut Seksyen (A–U)",
    selectMsicCode: "Pilih kod MSIC",
    searching: "Mencari...",
    noResults: "Tiada hasil. Cuba kata kunci lain.",
    noResultsLong: "Tiada hasil. Taip lebih banyak aksara atau cuba kata kunci lain.",
  },
  toast: {
    saved: "Disimpan",
    updated: "Dikemas kini",
    industrySet: "Industri ditetapkan",
    failedToLoadProfile: "Gagal memuatkan profil",
    failedToSaveTryAgain: "Gagal menyimpan. Sila cuba lagi.",
    couldNotSaveTryAgain: "Tidak dapat menyimpan sekarang. Sila cuba lagi.",
  },
  settings: {
    title: "Tetapan",
    subtitle: "Konfigurasi tambahan untuk keluaran akan datang.",
    prototypeOnlyTitle: "Prototaip sahaja",
    prototypeOnlyBody:
      "Dalam versi akan datang, skrin ini boleh menyimpan pilihan lanjutan. Buat masa ini, gunakan tab Akaun untuk akses profil, bahasa dan tema.",
  },
  dashboard: {
    title: "Profil",
    subtitle: "Paparan ringkas tetapan anda dan langkah seterusnya.",
    requiredMessage: "Wajib: Saiz syarikat dan MSIC untuk guna Semakan Invois.",
    completeMessage: "Profil lengkap. Anda boleh guna Semakan Invois.",
    allStepsCompleted: "Semua langkah selesai",
    finishToContinue: "Lengkapkan maklumat perniagaan dan industri untuk teruskan.",
  },
  setup: {
    title: "Profil perniagaan",
    progressOf: "daripada",
    progressCompleted: "lengkap",
    completeToUnlock: "Lengkapkan ini untuk buka Kiraan Cukai.",
    step: {
      business: { title: "Maklumat perniagaan", subtitle: "Nama, syarikat, saiz" },
      industry: { title: "Industri (MSIC)", subtitle: "Aktiviti ekonomi utama anda" },
      optional: { title: "Status SST", subtitle: "Butiran pendaftaran SST" },
    },
    optionalCard: {
      title: "Status SST",
    },
  },
  setupBusiness: {
    title: "Profil",
    subtitle: "Masukkan maklumat perniagaan anda.",
    namePlaceholder: "Nama anda",
    companySizeLabel: "Saiz syarikat tahun lepas",
    companySizePlaceholder: "Pilih saiz syarikat",
    companySize: {
      micro: "Mikro",
      small: "Kecil",
      medium: "Sederhana",
    },
  },
  setupOptional: {
    title: "Pendaftaran SST (Pilihan)",
    subtitle: "Membantu kami beri keputusan lebih tepat. Anda boleh langkau dan masih guna Kiraan Cukai.",
    info: {
      whyWeAsk: {
        title: "Mengapa kami tanya",
        body: "Jika anda berdaftar SST, kami boleh paparkan keputusan dengan nota pematuhan yang lebih jelas (cth: kelayakan kredit cukai input / konteks pendaftaran).",
      },
      ifYouSkip: {
        title: "Jika anda langkau",
        body: "Kami masih jalankan Kiraan Cukai, tetapi keputusan mungkin kurang spesifik.",
      },
      whereToFind: {
        title: "Di mana untuk cari",
        body: "Semak sijil/portal/akauntan pendaftaran SST anda. Nombor SST biasanya bermula dengan 'SST'.",
      },
    },
    question: "Adakah anda berdaftar SST?",
    notSureHint: "Pilih 'Tidak pasti' jika anda belum tahu.",
    sstNumberLabel: "Nombor pendaftaran SST",
    sstNumberPlaceholder: "cth: SST-XXXXXXX",
    effectiveDateLabel: "Tarikh berkuat kuasa",
    effectiveDateHint: "Tarikh berkuat kuasa = tarikh pendaftaran anda menjadi aktif.",
    errors: {
      sstNumberRequired: "Nombor SST diperlukan",
      effectiveDateRequired: "Tarikh berkuat kuasa diperlukan",
    },
    noMessage: "Anda masih boleh guna Kiraan Cukai. Kami anggap anda tidak berdaftar.",
    notSureMessage: "Tiada masalah — anda boleh kemas kini ini kemudian dalam Tetapan.",
  },
  setupIndustry: {
    title: "Industri (MSIC)",
    subtitle: "Cari menggunakan kod atau nama MSIC.",
    sectionTitle: "Industri (MSIC)",
    errors: { msicRequired: "Pemilihan MSIC diperlukan." },
    loadingIndustryDetails: "Memuatkan butiran industri...",
    selectedIndustry: "Industri dipilih",
    industryCodeNotFoundPrefix: "Kod industri",
    industryCodeNotFoundSuffix: "tidak ditemui",
    viewScope: "Lihat skop",
    scopeTitle: "Skop Aktiviti Ekonomi",
    scope: {
      section: "Seksyen",
      division: "Bahagian",
      group: "Kumpulan",
      class: "Kelas",
    },
    invoice: {
      type: "Jenis",
      sales: "Jualan",
      cost: "Kos",
      item: "Item",
      itemsHint: "Item adalah berdasarkan skop MSIC yang anda pilih.",
      noItemsAvailable: "Tiada item tersedia",
      itemPlaceholder: "Cari atau pilih item...",
      checking: "Menyemak...",
      checkInvoice: "Semak invois",
    },
    result: {
      sstRateNotAvailable: "Kadar SST belum tersedia.",
      noResultTitle: "Tiada keputusan untuk item ini buat masa ini",
      tryMsicLevel: "Sila cuba pada tahap MSIC",
    },
  },
  auth: {
    emailPlaceholder: "you@example.com",
    login: {
      title: "Selamat kembali",
      subtitle: "Log masuk ke akaun TaxApp anda",
      signingIn: "Sedang log masuk...",
      signIn: "Log masuk",
      noAccount: "Tiada akaun?",
      signUp: "Daftar",
      unexpectedError: "Ralat tidak dijangka berlaku. Sila cuba lagi.",
    },
    signup: {
      title: "Cipta akaun",
      subtitle: "Daftar untuk mula menggunakan TaxApp",
      passwordHint: "Mesti sekurang-kurangnya 6 aksara",
      confirmPasswordLabel: "Sahkan kata laluan",
      creatingAccount: "Sedang cipta akaun...",
      signUp: "Daftar",
      haveAccount: "Sudah ada akaun?",
      signIn: "Log masuk",
      success: {
        checkEmailToConfirm: "Akaun dicipta. Semak e-mel anda untuk pengesahan.",
      },
      errors: {
        invalidEmail: "Sila masukkan e-mel yang sah.",
        passwordTooShort: "Kata laluan mesti sekurang-kurangnya 6 aksara.",
        passwordsDoNotMatch: "Kata laluan tidak sepadan.",
        passwordsDoNotMatchInline: "Kata laluan tidak sepadan",
        networkError:
          "Ralat rangkaian: tidak dapat menghubungi perkhidmatan pengesahan. Semak sambungan dan pembolehubah persekitaran Supabase.",
        signUpFailed: "Pendaftaran gagal. Sila cuba lagi.",
      },
    },
  },
  account: {
    title: "Akaun",
    subtitle: "Tetapan untuk profil dan pengalaman aplikasi anda.",
    backToDashboard: "Kembali ke papan pemuka",
    profile: {
      title: "Profil",
      description: "Pautan pantas ke tetapan teras anda.",
      setup: "Tetapan profil",
    },
    settings: {
      title: "Tetapan",
      description: "Bagaimana TaxApp kelihatan dan dirasai.",
      language: "Bahasa",
      theme: "Tema",
      fontSize: "Saiz fon",
      languageOptions: {
        en: "English",
        ms: "Bahasa Melayu",
        iban: "Iban (Akan datang)",
        zh: "中文 (Akan datang)",
      },
    },
    support: {
      title: "Sokongan & keselamatan",
      description: "Bantuan untuk anda dan perlindungan untuk data anda.",
      help: "Bantuan & maklum balas",
      soon: "Akan datang",
      security: "Keselamatan & privasi",
      placeholder: "Pemegang tempat",
      signOut: "Log keluar",
    },
  },
};
