export const ms = {
  nav: {
    home: "Utama",
    account: "Akaun",
    settings: "Tetapan",
    openAccount: "Buka akaun",
  },
  common: {
    partners: "Rakan kongsi",
    sarawakOnly: "Sarawak sahaja",
    back: "Kembali",
    loading: "Memuatkan...",
    openArrow: "Buka →",
    required: "Wajib",
    optional: "Pilihan",
    done: "Selesai",
    incomplete: "Belum lengkap",
    save: "Simpan",
    saving: "Menyimpan...",
    continue: "Teruskan",
    saveAndContinue: "Simpan dan teruskan",
    saveProfile: "Simpan profil",
    continueArrow: "Teruskan →",
    completeRequiredFields: "Lengkapkan medan wajib untuk teruskan.",
    yes: "Ya",
    no: "Tidak",
    notSure: "Tidak pasti",
    email: "E-mel",
    password: "Kata laluan",
    name: "Nama",
  },
  theme: {
    light: "Cerah",
    dark: "Gelap",
    system: "Sistem",
  },
  fontSize: {
    small: "Kecil",
    medium: "Sederhana",
    large: "Besar",
    largePlus: "Besar+",
  },
  msicPicker: {
    title: "Pilih Industri (MSIC)",
    subtitle: "Cari menggunakan kod atau nama",
    searchPlaceholder: "Cari kod MSIC (cth. 47110) atau nama (cth. runcit)",
    recent: "Terkini:",
    examples: "Contoh:",
    startTyping: "Mula menaip untuk mencari kod MSIC atau nama industri.",
    browseBySection: "Lihat mengikut Seksyen (A–U)",
    selectMsicCode: "Pilih kod MSIC",
    searching: "Mencari...",
    noResults: "Tiada hasil. Cuba kata kunci lain.",
    noResultsLong: "Tiada hasil. Taip lebih banyak aksara atau cuba kata kunci lain.",
    others: {
      buttonLabel: "Lain-lain — Masukkan secara manual",
      buttonHint: "Taipkan kod MSIC dan keterangan perniagaan anda.",
      linkLabel: "Tak jumpa? Masukkan secara manual",
      title: "Masukkan MSIC secara manual",
      subtitle: "Taipkan kod industri dan keterangan ringkas.",
      codeLabel: "Kod MSIC",
      codePlaceholder: "cth. 47190",
      descriptionLabel: "Keterangan perniagaan",
      descriptionPlaceholder: "cth. Jualan runcit barangan lain",
      errorCodeRequired: "Kod MSIC diperlukan.",
      errorDescriptionRequired: "Keterangan perniagaan diperlukan.",
      toastSaved: "Disimpan — menunggu pengesahan.",
      pendingVerification: "Menunggu pengesahan",
    },
  },
  toast: {
    saved: "Disimpan",
    updated: "Dikemas kini",
    industrySet: "Industri ditetapkan",
    failedToLoadProfile: "Gagal memuatkan profil",
    failedToSaveTryAgain: "Gagal menyimpan. Sila cuba lagi.",
    couldNotSaveTryAgain: "Tidak dapat menyimpan sekarang. Sila cuba lagi.",
  },
  settings: {
    title: "Tetapan",
    subtitle: "Konfigurasi tambahan untuk keluaran akan datang.",
    prototypeOnlyTitle: "Prototaip sahaja",
    prototypeOnlyBody:
      "Dalam versi akan datang, skrin ini boleh menyimpan pilihan lanjutan. Buat masa ini, gunakan tab Akaun untuk akses profil, bahasa dan tema.",
  },
  dashboard: {
    title: "Profil",
    subtitle: "Paparan ringkas tetapan anda dan langkah seterusnya.",
    requiredMessage: "Wajib: Saiz syarikat dan MSIC untuk guna Semakan Invois.",
    completeMessage: "Profil lengkap. Anda boleh guna Semakan Invois.",
    allStepsCompleted: "Semua langkah selesai",
    finishToContinue: "Lengkapkan maklumat perniagaan dan industri untuk teruskan.",
  },
  setup: {
    title: "Profil perniagaan",
    progressOf: "daripada",
    progressCompleted: "lengkap",
    completeToUnlock: "Lengkapkan ini untuk buka Kiraan Cukai.",
    step: {
      business: { title: "Maklumat perniagaan", subtitle: "Nama, syarikat, saiz" },
      industry: { title: "Industri (MSIC)", subtitle: "Aktiviti ekonomi utama anda" },
      optional: { title: "Status SST", subtitle: "Butiran pendaftaran SST" },
    },
    optionalCard: {
      title: "Status SST",
    },
  },
  setupBusiness: {
    title: "Profil",
    subtitle: "Masukkan maklumat perniagaan anda.",
    namePlaceholder: "Nama anda",
    companyNameLabel: "Nama syarikat",
    companyNamePlaceholder: "cth. Acme Sdn Bhd",
    companySizeLabel: "Saiz syarikat tahun lepas",
    companySizePlaceholder: "Pilih saiz syarikat",
    companySize: {
      micro: "Mikro",
      small: "Kecil",
      medium: "Sederhana",
    },
  },
  setupOptional: {
    title: "Pendaftaran SST (Pilihan)",
    subtitle: "Membantu kami beri keputusan lebih tepat. Anda boleh langkau dan masih guna Kiraan Cukai.",
    info: {
      whyWeAsk: {
        title: "Mengapa kami tanya",
        body: "Jika anda berdaftar SST, kami boleh paparkan keputusan dengan nota pematuhan yang lebih jelas (cth: kelayakan kredit cukai input / konteks pendaftaran).",
      },
      ifYouSkip: {
        title: "Jika anda langkau",
        body: "Kami masih jalankan Kiraan Cukai, tetapi keputusan mungkin kurang spesifik.",
      },
      whereToFind: {
        title: "Di mana untuk cari",
        body: "Semak sijil/portal/akauntan pendaftaran SST anda. Nombor SST biasanya bermula dengan 'SST'.",
      },
    },
    question: "Adakah anda berdaftar SST?",
    notSureHint: "Pilih 'Tidak pasti' jika anda belum tahu.",
    sstNumberLabel: "Nombor pendaftaran SST",
    sstNumberPlaceholder: "cth: SST-XXXXXXX",
    effectiveDateLabel: "Tarikh berkuat kuasa",
    effectiveDateHint: "Tarikh berkuat kuasa = tarikh pendaftaran anda menjadi aktif.",
    errors: {
      sstNumberRequired: "Nombor SST diperlukan",
      effectiveDateRequired: "Tarikh berkuat kuasa diperlukan",
    },
    noMessage: "Anda masih boleh guna Kiraan Cukai. Kami anggap anda tidak berdaftar.",
    notSureMessage: "Tiada masalah — anda boleh kemas kini ini kemudian dalam Tetapan.",
  },
  setupIndustry: {
    title: "Industri (MSIC)",
    subtitle: "Cari menggunakan kod atau nama MSIC.",
    sectionTitle: "Industri (MSIC)",
    errors: { msicRequired: "Pemilihan MSIC diperlukan." },
    loadingIndustryDetails: "Memuatkan butiran industri...",
    selectedIndustry: "Industri dipilih",
    industryCodeNotFoundPrefix: "Kod industri",
    industryCodeNotFoundSuffix: "tidak ditemui",
    viewScope: "Lihat skop",
    scopeTitle: "Skop Aktiviti Ekonomi",
    scope: {
      section: "Seksyen",
      division: "Bahagian",
      group: "Kumpulan",
      class: "Kelas",
    },

    itemSst: {
  resultLabel: "Kadar SST yang berkenaan",
},

    itemSearch: {
      title: "Barang",
      hint: "Taip nama barang (cth. 'papan kekunci') untuk cari MSIC secara automatik.",
      placeholder: "cth. papan kekunci, pencetak, dll.",
      noMsic: "Barang ini belum ada MSIC. Sila pilih industri secara manual atau naik satu tahap.",
      notFound: "Tiada padanan untuk barang ini. Sila cuba kata kunci yang lebih luas atau naik satu tahap.",
      msicNotFound: "Kod MSIC tidak ditemui untuk barang ini.",
      msicAlreadySelected: "MSIC sudah dipilih — kosongkan untuk gunakan MSIC barang ini.",
      unclassifiedBadge: "Tanpa klasifikasi",
      addUnclassifiedLink: "Tambah ini sebagai barang tanpa klasifikasi baharu",
    },
    invoice: {
      type: "Jenis",
      sales: "Jualan",
      cost: "Kos",
      item: "Barang",
      itemsHint: "Barang adalah berdasarkan skop MSIC yang anda pilih.",
      noItemsAvailable: "Tiada barang tersedia",
      itemPlaceholder: "Cari atau pilih barang...",
      checking: "Menyemak...",
      checkInvoice: "Semak invois",
      checkTaxPercent: "Semak % cukai untuk invois",
    },
    result: {
      sstRateNotAvailable: "Kadar SST belum tersedia.",
      noResultTitle: "Tiada keputusan untuk barang ini buat masa ini",
      tryMsicLevel: "Sila cuba pada tahap MSIC",
    },
  },
  auth: {
    emailPlaceholder: "you@example.com",
    login: {
      title: "Selamat kembali",
      subtitle: "Log masuk ke akaun SmartTaxApp anda",
      signingIn: "Sedang log masuk...",
      signIn: "Log masuk",
      noAccount: "Tiada akaun?",
      signUp: "Daftar",
      forgotPassword: "Lupa kata laluan?",
      unexpectedError: "Ralat tidak dijangka berlaku. Sila cuba lagi.",
    },
    resetPassword: {
      title: "Lupa kata laluan",
      subtitle: "Masukkan e-mel anda untuk menerima kod 6 digit",
      helper: "Kami akan hantar kod ke e-mel yang digunakan semasa pendaftaran.",
      emailHint: "Kami akan hantar kod ke {email}",
      sending: "Menghantar...",
      sendCode: "Hantar kod",
      sendResetLink: "Hantar pautan set semula",
      resendCode: "Hantar kod lagi",
      resendIn: "Hantar lagi dalam {seconds}",
      backToLogin: "Kembali ke log masuk",
      changeEmail: "Tukar e-mel",
      codeSentMessage: "Kami telah hantar kod 6 digit ke e-mel anda.",
      useLatestCodeHint: "Gunakan kod terkini yang kami hantar.",
      stepBTitle: "Masukkan kod dan set kata laluan baharu",
      codeLabel: "Kod 6 digit",
      codePlaceholder: "000000",
      resetPasswordButton: "Set semula kata laluan",
      resetting: "Menetapkan semula...",
      successTitle: "Kata laluan dikemas kini",
      successMessage: "Pergi ke log masuk.",
      invalidOrExpiredCode: "Kod tidak sah atau tamat tempoh. Gunakan kod terkini yang kami hantar dan cuba lagi.",
      sessionMissingAfterVerify: "Tidak dapat mengesahkan kod. Sila minta kod baharu.",
      couldntUpdatePassword: "Tidak dapat mengemas kini kata laluan. Sila cuba lagi.",
      success: {
        title: "Semak e-mel anda",
        message: "Kami telah hantar kod 6 digit ke e-mel anda.",
        didntReceiveSendAgain: "Tidak terima e-mel? Hantar kod lagi.",
      },
      errors: {
        emailRequired: "E-mel diperlukan.",
        codeRequired: "Masukkan kod 6 digit.",
        codeMustBe6Digits: "Kod mesti 6 digit.",
        passwordTooShort: "Kata laluan mesti sekurang-kurangnya 6 aksara.",
        passwordsDoNotMatch: "Kata laluan tidak sepadan.",
        unexpectedError: "Ralat rangkaian atau pengesahan. Semak sambungan dan cuba lagi.",
        networkError: "Ralat rangkaian. Semak sambungan anda dan cuba lagi.",
      },
    },
    resetPasswordConfirm: {
      title: "Set kata laluan baharu",
      subtitle: "Masukkan kata laluan baharu anda di bawah.",
      newPasswordLabel: "Kata laluan baharu",
      confirmPasswordLabel: "Sahkan kata laluan",
      submit: "Kemas kini kata laluan",
      updating: "Mengemas kini...",
      loading: "Mengesahkan pautan set semula...",
      successTitle: "Kata laluan dikemas kini",
      successMessage: "Mengalihkan anda ke log masuk...",
      backToLogin: "Kembali ke log masuk",
      didntReceiveSendAgain: "Tidak terima e-mel? Hantar lagi.",
      requestNewLink: "Minta pautan baharu",
      goToForgotPassword: "Lupa kata laluan",
      errorNoLink: "Tiada pautan set semula dikesan. Gunakan pautan dari e-mel anda.",
      errorInvalidExpired: "Pautan ini tidak sah atau telah tamat tempoh. Minta pautan baharu.",
      errorExpiredTitle: "Pautan set semula tidak sah atau tamat tempoh",
      errorExpiredExplanation: "Pautan ini sekali guna dan mungkin telah dibuka oleh pengimbas keselamatan e-mel sebelum anda mengklik.",
      errorExpiredTip1: "Minta pautan baharu dan buka segera",
      errorExpiredTip2: "Buka e-mel pada telefon anda, pelanggan berbeza, atau dalam tetingkap peribadi/inkognito",
      errorExpiredTip3: "Salin URL set semula dari e-mel dan tampal ke bar alamat penyemak imbas (elakkan pratonton e-mel dalam aplikasi)",
      openLinkManuallyTitle: "Buka pautan secara manual",
      openLinkManuallyInstructions: "Salin URL set semula dari e-mel anda dan tampal ke bar alamat penyemak imbas. Elakkan membuka pautan dalam webview pratonton e-mel.",
      errors: {
        passwordTooShort: "Kata laluan mesti sekurang-kurangnya 6 aksara.",
        passwordsDoNotMatch: "Kata laluan tidak sepadan.",
        unexpectedError: "Ralat rangkaian atau pengesahan. Sila cuba lagi.",
      },
    },
    signup: {
      title: "Cipta akaun",
      subtitle: "Daftar untuk mula menggunakan SmartTaxApp",
      passwordHint: "Mesti sekurang-kurangnya 6 aksara",
      confirmPasswordLabel: "Sahkan kata laluan",
      creatingAccount: "Sedang cipta akaun...",
      signUp: "Daftar",
      haveAccount: "Sudah ada akaun?",
      signIn: "Log masuk",
      success: {
        checkEmailToConfirm: "Akaun dicipta. Semak e-mel anda untuk pengesahan.",
      },
      errors: {
        invalidEmail: "Sila masukkan e-mel yang sah.",
        passwordTooShort: "Kata laluan mesti sekurang-kurangnya 6 aksara.",
        passwordsDoNotMatch: "Kata laluan tidak sepadan.",
        passwordsDoNotMatchInline: "Kata laluan tidak sepadan",
        networkError:
          "Ralat rangkaian: tidak dapat menghubungi perkhidmatan pengesahan. Semak sambungan dan pembolehubah persekitaran Supabase.",
        signUpFailed: "Pendaftaran gagal. Sila cuba lagi.",
      },
    },
  },
  admin: {
    addUnclassifiedTitle: "Tambah Barang (Tanpa Klasifikasi)",
    addUnclassifiedSubtitle: "Taipkan barang yang anda jual atau beli (cth. 'kaca') untuk cari MSIC secara automatik.",
    itemNameLabel: "Nama barang",
    itemNamePlaceholder: "cth. Stick gam",
    tagsLabel: "Tag",
    tagsPlaceholder: "cth. pejabat, bekalan",
    tagsHint: "Tag dipisahkan koma untuk carian",
    submit: "Hantar",
    submitting: "Menghantar...",
    successTitle: "Dihantar",
    successThankYou: "Terima kasih! Pasukan kami akan semak.",
    addAnother: "Tambah lagi",
    toastItemNameRequired: "Nama barang diperlukan.",
    backToHome: "← Kembali ke Utama",
    usageLabel: "Apa yang anda buat dengan barang ini?",
    usageHint: "Ini membantu kami menetapkan kod industri yang betul.",
    usageSell: "Saya jual",
    usageBuy: "Saya beli / guna",
    activityLabel: "Aktiviti perniagaan",
    activityPlaceholder: "cth. Pembuatan botol kaca, Jualan runcit produk kaca",
    activityHint: "Jelaskan secara ringkas apa perniagaan anda buat dengan barang ini.",
    toastUsageRequired: "Sila pilih sama ada anda jual atau beli barang ini.",
  },
  account: {
    title: "Akaun",
    subtitle: "Tetapan untuk profil dan pengalaman aplikasi anda.",
    backToDashboard: "Kembali ke papan pemuka",
    profile: {
      title: "Profil",
      description: "Pautan pantas ke tetapan teras anda.",
      setup: "Tetapan profil",
    },
    changePassword: {
      title: "Tukar kata laluan",
      description: "Kemas kini kata laluan anda. Tiada e-mel akan dihantar.",
      currentPasswordLabel: "Kata laluan semasa",
      currentPasswordOptional: "(pilihan)",
      newPasswordLabel: "Kata laluan baharu",
      confirmPasswordLabel: "Sahkan kata laluan",
      submit: "Kemas kini kata laluan",
      updating: "Mengemas kini...",
      success: "Kata laluan dikemas kini.",
      changePasswordCta: "Tukar kata laluan",
      passwordHint: "Sekurang-kurangnya 6 aksara.",
      errors: {
        newPasswordRequired: "Kata laluan baharu diperlukan.",
        passwordTooShort: "Kata laluan mesti sekurang-kurangnya 6 aksara.",
        passwordsDoNotMatch: "Kata laluan tidak sepadan.",
        currentPasswordIncorrect: "Kata laluan semasa tidak betul.",
        unexpectedError: "Tidak dapat kemas kini kata laluan. Sila cuba lagi.",
      },
    },
    password: {
      title: "Kata laluan",
      description: "Tukar kata laluan anda atau minta pautan set semula dihantar ke e-mel anda.",
      helper: "Untuk keselamatan, kami tidak menghantar kata laluan melalui e-mel. Anda akan tetapkan yang baharu.",
      changePasswordCta: "Tukar kata laluan sekarang",
      sendResetInstead: "Hantar e-mel set semula kata laluan",
      cancel: "Batal",
      sendResetEmail: "Hantar pautan set semula",
      sending: "Menghantar...",
      success: "Semak e-mel anda untuk pautan set semula.",
    },
    settings: {
      title: "Tetapan",
      description: "Bagaimana SmartTaxApp kelihatan dan dirasai.",
      language: "Bahasa",
      theme: "Tema",
      fontSize: "Saiz fon",
      languageOptions: {
        en: "English",
        ms: "Bahasa Melayu",
        iban: "Iban (Akan datang)",
        zh: "中文 (Akan datang)",
      },
    },
    support: {
      title: "Sokongan & keselamatan",
      description: "Bantuan untuk anda dan perlindungan untuk data anda.",
      help: "Bantuan & maklum balas",
      whatsAppCta: "Sembang",
      soon: "Akan datang",
      security: "Keselamatan & privasi",
      placeholder: "Pemegang tempat",
      signOut: "Log keluar",
    },
  },
};